Add feature to configure OAuth2.0 for HTTP endpoints
wso2/wso2-synapse pull request #1645
Opened 2020-10-15 04:42 UTC by SanojPunchihewa

This PR allows the user to configure the following OAuth grant types for HTTP endpoints

**Authorization Code grant type (Refresh token grant type)**
```xml
<endpoint name="FoodEP" xmlns="http://ws.apache.org/ns/synapse">
    <http method="get" uri-template="http://localhost:9192/service/foodservice">
        <authentication>
            <oauth>
                <authorizationCode>
                    <clientId>clientId</clientId>
                    <clientSecret>clientSecret</clientSecret>
                    <refreshToken>refreshToken</refreshToken>
                    <tokenUrl>oauthServerUrl</tokenUrl>
                </authorizationCode>
            </oauth>
        </authentication>
    </http>
</endpoint>
```

**Client Credentials grant type**
```xml
<endpoint name="FoodEP" xmlns="http://ws.apache.org/ns/synapse">
    <http method="get" uri-template="http://localhost:9192/service/foodservice">
        <authentication>
            <oauth>
                <clientCredentials>
                    <clientId>clientId</clientId>
                    <clientSecret>clientSecret</clientSecret>
                    <tokenUrl>oauthServerUrl</tokenUrl>
                </clientCredentials>
            </oauth>
        </authentication>
    </http>
</endpoint>
```

2020-11-04 17:51 UTC, Asitha requested changes

2020-11-06 10:52 UTC, SanojPunchihewa commented on modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java
> +    public void setOauthHandler(OAuthHandler oauthHandler) {
Fixed with c72ec01

2020-11-06 10:54 UTC, SanojPunchihewa commented on modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java
> +    public OAuthHandler getOauthHandler() {
Fixed with 64376e2

2021-01-17 09:24 UTC, Asitha approved these changes

2021-01-18 06:52 UTC, merged